# -*- coding: utf-8 -*-

import unittest

import dbops


class MyTestCase(unittest.TestCase):
    def setUp(self):
        self.dbops = dbops.DBOps()
        self.users_objects = [{u'contributors_enabled': False,
                               u'created_at': u'Wed Jan 06 17:19:59 +0000 2010',
                               u'default_profile': False,
                               u'default_profile_image': False,
                               u'description': u'Prevajalec, programer, plesalec, Pirat. Ni da ni!',
                               u'entities': {u'description': {u'urls': []},
                                             u'url': {u'urls': [{
                                                                    u'display_url': u'benjamin.ferreira.si',
                                                                    u'expanded_url': u'http://benjamin.ferreira.si',
                                                                    u'indices': [
                                                                        0, 22],
                                                                    u'url': u'http://t.co/y4SiWDc7au'}]}},
                               u'favourites_count': 199,
                               u'follow_request_sent': False,
                               u'followers_count': 232,
                               u'following': False,
                               u'friends_count': 115,
                               u'geo_enabled': False,
                               u'id': 102426448,
                               u'id_str': u'102426448',
                               u'is_translation_enabled': False,
                               u'is_translator': False,
                               u'lang': u'en',
                               u'listed_count': 10,
                               u'location': u'Slovenia',
                               u'name': u'Rolando B V Ferreira',
                               u'notifications': False,
                               u'profile_background_color': u'1A1B1F',
                               u'profile_background_image_url': u'http://abs.twimg.com/images/themes/theme9/bg.gif',
                               u'profile_background_image_url_https': u'https://abs.twimg.com/images/themes/theme9/bg.gif',
                               u'profile_background_tile': False,
                               u'profile_image_url': u'http://pbs.twimg.com/profile_images/453251876231081984/upb1vNhd_normal.jpeg',
                               u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/453251876231081984/upb1vNhd_normal.jpeg',
                               u'profile_link_color': u'000000',
                               u'profile_location': None,
                               u'profile_sidebar_border_color': u'000000',
                               u'profile_sidebar_fill_color': u'252429',
                               u'profile_text_color': u'666666',
                               u'profile_use_background_image': True,
                               u'protected': False,
                               u'screen_name': u'benjiferreira',
                               u'status': {u'contributors': None,
                                           u'coordinates': None,
                                           u'created_at': u'Wed Mar 11 11:53:18 +0000 2015',
                                           u'entities': {
                                               u'hashtags': [
                                                   {u'indices': [53, 64],
                                                    u'text': u'referendum'},
                                                   {u'indices': [65, 82],
                                                    u'text': u'druzinskizakonik'},
                                                   {u'indices': [83, 88],
                                                    u'text': u'lgbt'}],
                                               u'symbols': [],
                                               u'urls': [{
                                                             u'display_url': u'zasanjana.si/2015/03/10/hom\u2026',
                                                             u'expanded_url': u'http://www.zasanjana.si/2015/03/10/homo-slovenus-sofisticadis/',
                                                             u'indices': [30,
                                                                          52],
                                                             u'url': u'http://t.co/06laP6RiYV'}],
                                               u'user_mentions': [
                                                   {u'id': 111279524,
                                                    u'id_str': u'111279524',
                                                    u'indices': [89, 101],
                                                    u'name': u'Mitja Blazic',
                                                    u'screen_name': u'MitjaBlazic'},
                                                   {u'id': 187975349,
                                                    u'id_str': u'187975349',
                                                    u'indices': [102,
                                                                 113],
                                                    u'name': u'Matic Munc',
                                                    u'screen_name': u'monster189'}]},
                                           u'favorite_count': 2,
                                           u'favorited': False,
                                           u'geo': None,
                                           u'id': 575625541480542208L,
                                           u'id_str': u'575625541480542208',
                                           u'in_reply_to_screen_name': None,
                                           u'in_reply_to_status_id': None,
                                           u'in_reply_to_status_id_str': None,
                                           u'in_reply_to_user_id': None,
                                           u'in_reply_to_user_id_str': None,
                                           u'lang': u'sl',
                                           u'place': None,
                                           u'possibly_sensitive': False,
                                           u'retweet_count': 2,
                                           u'retweeted': False,
                                           u'source': u'<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
                                           u'text': u'Agreed! J**** refefendopapke! http://t.co/06laP6RiYV #referendum #druzinskizakonik #lgbt @MitjaBlazic @monster189 u\u017eivajta v dobrem branju=)',
                                           u'truncated': False},
                               u'statuses_count': 629,
                               u'time_zone': u'Athens',
                               u'url': u'http://t.co/y4SiWDc7au',
                               u'utc_offset': 7200,
                               u'verified': False},
                              {u'contributors_enabled': False,
                               u'created_at': u'Sat Jul 02 17:41:15 +0000 2011',
                               u'default_profile': False,
                               u'default_profile_image': False,
                               u'description': u"Web developer (PHP, Symfony2) & Pirate. Interested in politics, science, social issues, rationality & indie games when I'm lazy. Secretary of @piratskastranka",
                               u'entities': {u'description': {u'urls': []},
                                             u'url': {u'urls': [{
                                                                    u'display_url': u'thescepticalpirate.eu',
                                                                    u'expanded_url': u'http://thescepticalpirate.eu/',
                                                                    u'indices': [
                                                                        0, 22],
                                                                    u'url': u'http://t.co/tfzPOKgE54'}]}},
                               u'favourites_count': 38,
                               u'follow_request_sent': False,
                               u'followers_count': 195,
                               u'following': True,
                               u'friends_count': 260,
                               u'geo_enabled': True,
                               u'id': 328071700,
                               u'id_str': u'328071700',
                               u'is_translation_enabled': False,
                               u'is_translator': False,
                               u'lang': u'en',
                               u'listed_count': 15,
                               u'location': u'Ljubljana, Slovenia',
                               u'name': u'Rok Andr\xe9e',
                               u'notifications': False,
                               u'profile_background_color': u'1A1B1F',
                               u'profile_background_image_url': u'http://abs.twimg.com/images/themes/theme9/bg.gif',
                               u'profile_background_image_url_https': u'https://abs.twimg.com/images/themes/theme9/bg.gif',
                               u'profile_background_tile': False,
                               u'profile_image_url': u'http://pbs.twimg.com/profile_images/552053403204210688/4hntX7bz_normal.jpeg',
                               u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/552053403204210688/4hntX7bz_normal.jpeg',
                               u'profile_link_color': u'2FC2EF',
                               u'profile_location': None,
                               u'profile_sidebar_border_color': u'181A1E',
                               u'profile_sidebar_fill_color': u'252429',
                               u'profile_text_color': u'666666',
                               u'profile_use_background_image': True,
                               u'protected': False,
                               u'screen_name': u'pu7r',
                               u'status': {u'contributors': None,
                                           u'coordinates': None,
                                           u'created_at': u'Sat Mar 14 09:55:55 +0000 2015',
                                           u'entities': {
                                               u'hashtags': [
                                                   {u'indices': [125, 134],
                                                    u'text': u'ignoring'}],
                                               u'symbols': [],
                                               u'urls': [
                                                   {
                                                       u'display_url': u'thecalmzone.net',
                                                       u'expanded_url': u'https://www.thecalmzone.net/',
                                                       u'indices': [49, 72],
                                                       u'url': u'https://t.co/ugGtxLuiRs'}],
                                               u'user_mentions': [
                                                   {u'id': 187975349,
                                                    u'id_str': u'187975349',
                                                    u'indices': [0, 11],
                                                    u'name': u'Matic Munc',
                                                    u'screen_name': u'monster189'}]},
                                           u'favorite_count': 0,
                                           u'favorited': False,
                                           u'geo': None,
                                           u'id': 576683163369517056L,
                                           u'id_str': u'576683163369517056',
                                           u'in_reply_to_screen_name': u'monster189',
                                           u'in_reply_to_status_id': 576678630232838144L,
                                           u'in_reply_to_status_id_str': u'576678630232838144',
                                           u'in_reply_to_user_id': 187975349,
                                           u'in_reply_to_user_id_str': u'187975349',
                                           u'lang': u'sl',
                                           u'place': None,
                                           u'possibly_sensitive': False,
                                           u'retweet_count': 0,
                                           u'retweeted': False,
                                           u'source': u'<a href="https://about.twitter.com/products/tweetdeck" rel="nofollow">TweetDeck</a>',
                                           u'text': u'@monster189 Oni se \u017ee borijo proti trendu z CALM https://t.co/ugGtxLuiRs\nPri nas ~400 samomorov/leto vs ~100 smrti na cesti. #ignoring',
                                           u'truncated': False},
                               u'statuses_count': 1680,
                               u'time_zone': u'Ljubljana',
                               u'url': u'http://t.co/tfzPOKgE54',
                               u'utc_offset': 3600,
                               u'verified': False}]

    def tearDown(self):
        pass

    def test_save_users_to_db(self):
        self.dbops.save_users_to_db(self.users_objects)


if __name__ == '__main__':
    unittest.main()
